apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image-signature
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: verify-image-signature
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "*"  # Apply to all images
          attestors:
            - count: 1
              entries:
                - keys:
                    publicKeys: |-
                      -----BEGIN PUBLIC KEY-----
                      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEio6clQ4tPxk7HEUPHLZnMgS+AnCA
                      /rLW7RGi710oah5+Q5M1zJk/OMDtCI2LsvwhaiyqrZYAF4uMXeEEkzv7Lw==
                      -----END PUBLIC KEY-----
